### ISSUE TITLE
home_dir not defined

### ISSUE THREAD

**Issue by okyeron** [itsyourbedtime/reels#1]
A couple issues....

`tab.save(reel, home_dir.."/dust/data/reels/".. txt ..".reel")`

`home_dir` is not defined 

For 2.0 you can use `_path.home` or `_path.dust`

for 2.0 compatibility you will want to just save to your data folder in the same directory as the script. 
```
if util.file_exists(_path.dust .. "reels/data") == false then
util.make_dir(_path.dust .. "reels/data")
end
```
then
`tab.save(reel, _path.dust .. "reels/data".. txt ..".reel")`

**Comment by itsyourbedtime** [comment]
Missed that somehow.
